#### <strong>Question 5: Functions and Arithmetic</strong>

---
<strong>Description</strong>: The government needs to calculate the total investment for projects with high location efficiency.

<strong>Task:</strong>
<ul>
    <li>Define a function calculate_total_investment that takes a list of Project_IDs and merged data from Geospatial_Dataset.xlsx and Financial_Dataset.xlsx.
    <li>Use a for loop to sum Investment_Cost for projects where Efisiensi_Lokasi == "High".
    <li>Return and display the total.
</ul>

<strong>Example Output:</strong>  
Total Investment for High-Efficiency Locations: 875.73 billion Rp

---

##### <strong>🔹Prepare Dataset</strong>

In [1]:
# import pandas untuk mengelola data
import pandas as pd

# membaca file excel geospatial dataset
df_geo = pd.read_excel('assets/Geospatial_Dataset.xlsx')

# melihat preview data geospatial
df_geo.head()

,Project_ID,Solar_Irradiance,Water_Flow,Distance_to_Grid,Konteks_Geospasial,Efisiensi_Lokasi
0,PLTS-NTT-001,5.8,0.0,8,"Sumba: radiasi tinggi, dekat jaringan",High: 📍📍📍📍
1,PLTM-SUMUT-001,0.0,1.5,5,"Tapanuli: debit stabil, akses PLN baik",High: 📍📍📍📍
2,PLTS-JATIM-001,5.5,0.0,3,"Surabaya: radiasi baik, jaringan dekat",High: 📍📍📍📍📍
3,PLTM-KALB-001,0.0,1.8,10,"Kalbar: debit tinggi, jaringan sedang",Medium: 📍📍📍
4,PLTS-SULS-001,5.7,0.0,6,"Makassar: radiasi tinggi, akses baik",High: 📍📍📍📍

In [2]:
# membaca file excel financial dataset
df_finance = pd.read_excel('assets/Financial_Dataset.xlsx')

# melihat preview data financial
df_finance.head()

,Project_ID,Investment_Cost,Revenue_Stream,Debt_Ratio,Payment_Delay,Konteks_Proyek,Status_Rank
0,PLTS-NTT-001,150.00,12.5,0.65,30,"PLTS di Sumba, biaya logistik tinggi, pendanaa...",Medium: ★★★☆☆
1,PLTM-SUMUT-001,80.00,6.8,0.55,15,"PLTM di Tapanuli, akses mudah ke jaringan PLN",Low: ★★☆☆☆
2,PLTS-JATIM-001,200.23,18.0,0.70,45,"PLTS besar di Surabaya, permintaan pasar tinggi",High: ★★★★☆
3,PLTM-KALB-001,90.00,7.2,0.60,20,"PLTM di Kalimantan Barat, tantangan lahan adat",Medium: ★★★☆☆
4,PLTS-SULS-001,125.50,10.0,0.50,10,"PLTS di Makassar, efisiensi tinggi distribusi",Low: ★☆☆☆☆

##### <strong>🔹Merge Dataset</strong>

In [3]:
# menggabungkan data geospatial dan financial berdasarkan project_ID dengan metode outer untuk menghindari kehilangan data
df_merged = pd.merge(df_geo, df_finance, on='Project_ID', how='outer')

# melihat preview data gabungan
df_merged.head()

,Project_ID,Solar_Irradiance,Water_Flow,Distance_to_Grid,Konteks_Geospasial,Efisiensi_Lokasi,Investment_Cost,Revenue_Stream,Debt_Ratio,Payment_Delay,Konteks_Proyek,Status_Rank
0,PLTM-ACHD-001,0.0,1.6,7,"Aceh: debit stabil, akses sedang",Medium: 📍📍📍,85.0,6.5,0.58,12,"PLTM di Aceh, akses sungai stabil",Low: ★★☆☆☆
1,PLTM-KALB-001,0.0,1.8,10,"Kalbar: debit tinggi, jaringan sedang",Medium: 📍📍📍,90.0,7.2,0.60,20,"PLTM di Kalimantan Barat, tantangan lahan adat",Medium: ★★★☆☆
2,PLTM-PAPU-001,0.0,2.0,15,"Papua: debit kuat, jaringan jauh",Low: 📍📍,100.0,8.0,0.75,60,"PLTM di Papua, lokasi terisolasi, risiko tinggi",High: ★★★★★
3,PLTM-SULU-001,0.0,1.7,12,"Sulut: debit baik, jaringan agak jauh",Medium: 📍📍📍,95.0,7.5,0.62,18,"PLTM di Sulawesi Utara, dukungan lokal baik",Medium: ★★★☆☆
4,PLTM-SUMUT-001,0.0,1.5,5,"Tapanuli: debit stabil, akses PLN baik",High: 📍📍📍📍,80.0,6.8,0.55,15,"PLTM di Tapanuli, akses mudah ke jaringan PLN",Low: ★★☆☆☆

##### <strong>🔹Define Function, Filter Location Efficiency</strong>

In [ ]:
# membuat fungsi calculate_total_investment yang menerima list project
def calculate_total_investment(list):
    # inisiasi variabel total_investment
    total_investment = 0
    # melakukan looping pada data di list
    for data in list:
        # memfilter data yang mempunyai efisiensi lokasi tinggi (High)
        if data['Efisiensi_Lokasi'][0:data['Efisiensi_Lokasi'].index(':')] == 'High':
            # menjumlahkan total investasi dari data yang di filter
            total_investment = total_investment + data['Investment_Cost']
    # mengembalikan nilai total investasi
    return total_investment

##### <strong>🔹Contain Data to List, Loop Dataset, Display Data</strong>

In [ ]:
# inisiasi list kosong
project_list = []

# melakukan looping dari data gabungan
for index, row in df_merged.iterrows():
    project = row['Project_ID']
    eff_lokasi = row['Efisiensi_Lokasi']
    investasi = row['Investment_Cost']
    # menambahkan data project ID, efisiensi lokasi, dan biaya investasi ke dalam project_list
    project_list.append({'Project_ID':project,'Efisiensi_Lokasi':eff_lokasi, 'Investment_Cost':investasi})

# memanggil fungsi calculate_total_investment dengan input project_list
print(f'Total Investment for High-Efficiency Locations: {calculate_total_investment(project_list)} billion Rp')

Total Investment for High-Efficiency Locations: 955.73 billion Rp

<strong>🔹Example Output:</strong>  
Total Investment for High-Efficiency Locations: 875.73 billion Rp