#### <strong>Question 1: Conditional Statements (If-Else) and Arithmetic Operations</strong>

---
<strong>Description</strong>: The government seeks to identify PLTS projects with high CO2 reduction efficiency per unit of investment, calculated as CO2 reduction per million rupiah.

<strong>Task:</strong>
<ul>
    <li>Merge Environmental_Dataset.xlsx and Financial_Dataset.xlsx using Project_ID.
    <li>For PLTS projects (Project_ID starts with "PLTS"), compute the ratio: CO2_Reduction / (Investment_Cost * 1_000_000).
    <li>Use if-else to classify the ratio as "High" (â‰¥ 0.5 tons CO2e/million Rp) or "Low" (< 0.5).
    <li>Display results as: "Project_ID: Ratio (Category)" using f-strings.
</ul>

<strong>Example Output:</strong>  
PLTS-NTT-001: 0.50 (High)  
PLTS-JATIM-001: 0.45 (Low)

---

##### <strong>ðŸ”¹Prepare Dataset</strong>

In [1]:
# import pandas untuk mengelola data
import pandas as pd

# membaca file excel environmental dataset
df_environmental = pd.read_excel('assets/Environmental_Dataset.xlsx')

# melihat preview data environmental
df_environmental.head()

,Project_ID,CO2_Reduction,Energy_Output,Environmental_Risk_Index,Konteks_Lingkungan,Peringkat_Dampak
0,PLTS-NTT-001,75000,25000,45,"Sumba: radiasi matahari tinggi, rawan kekeringan",High: ðŸŒ¿ðŸŒ¿ðŸŒ¿ðŸŒ¿
1,PLTM-SUMUT-001,30000,10000,60,"Tapanuli: banjir musiman, debit air stabil",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿
2,PLTS-JATIM-001,90000,30000,30,"Surabaya: risiko rendah, efisiensi tinggi",High: ðŸŒ¿ðŸŒ¿ðŸŒ¿ðŸŒ¿ðŸŒ¿
3,PLTM-KALB-001,35000,12000,55,"Kalbar: rawan banjir, hutan lindung dekat",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿
4,PLTS-SULS-001,60000,20000,40,"Makassar: cuaca stabil, risiko sedang",High: ðŸŒ¿ðŸŒ¿ðŸŒ¿ðŸŒ¿

In [2]:
# membaca file excel financial dataset
df_finance = pd.read_excel('assets/Financial_Dataset.xlsx')

# melihat preview data financial
df_finance.head()

,Project_ID,Investment_Cost,Revenue_Stream,Debt_Ratio,Payment_Delay,Konteks_Proyek,Status_Rank
0,PLTS-NTT-001,150.00,12.5,0.65,30,"PLTS di Sumba, biaya logistik tinggi, pendanaa...",Medium: â˜…â˜…â˜…â˜†â˜†
1,PLTM-SUMUT-001,80.00,6.8,0.55,15,"PLTM di Tapanuli, akses mudah ke jaringan PLN",Low: â˜…â˜…â˜†â˜†â˜†
2,PLTS-JATIM-001,200.23,18.0,0.70,45,"PLTS besar di Surabaya, permintaan pasar tinggi",High: â˜…â˜…â˜…â˜…â˜†
3,PLTM-KALB-001,90.00,7.2,0.60,20,"PLTM di Kalimantan Barat, tantangan lahan adat",Medium: â˜…â˜…â˜…â˜†â˜†
4,PLTS-SULS-001,125.50,10.0,0.50,10,"PLTS di Makassar, efisiensi tinggi distribusi",Low: â˜…â˜†â˜†â˜†â˜†

##### <strong>ðŸ”¹Merge Dataset</strong>

In [3]:
# menggabungkan data environmental dan financial berdasarkan project_ID dengan metode outer untuk menghindari kehilangan data
df_merged = pd.merge(df_environmental, df_finance, on='Project_ID', how='outer')

# melihat preview data gabungan
df_merged.head()

,Project_ID,CO2_Reduction,Energy_Output,Environmental_Risk_Index,Konteks_Lingkungan,Peringkat_Dampak,Investment_Cost,Revenue_Stream,Debt_Ratio,Payment_Delay,Konteks_Proyek,Status_Rank
0,PLTM-ACHD-001,32000,11000,65,"Aceh: banjir musiman, sungai kuat",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿,85.0,6.5,0.58,12,"PLTM di Aceh, akses sungai stabil",Low: â˜…â˜…â˜†â˜†â˜†
1,PLTM-KALB-001,35000,12000,55,"Kalbar: rawan banjir, hutan lindung dekat",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿,90.0,7.2,0.60,20,"PLTM di Kalimantan Barat, tantangan lahan adat",Medium: â˜…â˜…â˜…â˜†â˜†
2,PLTM-PAPU-001,40000,15000,70,"Papua: gempa tinggi, akses sulit",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿,100.0,8.0,0.75,60,"PLTM di Papua, lokasi terisolasi, risiko tinggi",High: â˜…â˜…â˜…â˜…â˜…
3,PLTM-SULU-001,36000,13000,50,"Sulut: gempa sedang, debit air baik",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿,95.0,7.5,0.62,18,"PLTM di Sulawesi Utara, dukungan lokal baik",Medium: â˜…â˜…â˜…â˜†â˜†
4,PLTM-SUMUT-001,30000,10000,60,"Tapanuli: banjir musiman, debit air stabil",Medium: ðŸŒ¿ðŸŒ¿ðŸŒ¿,80.0,6.8,0.55,15,"PLTM di Tapanuli, akses mudah ke jaringan PLN",Low: â˜…â˜…â˜†â˜†â˜†

##### <strong>ðŸ”¹Compute, Classify, Filter Ratio</strong>

In [4]:
# melakukan looping dari data gabungan
for index, row in df_merged.iterrows():
    # memfilter data PLTS
    if row['Project_ID'].startswith('PLTS'):
        # menghitung ratio CO2 Reduction dengan biaya investasi
        ratio = (row['CO2_Reduction']) / (row['Investment_Cost'] * 1000000)
        # mengkategorikan ratio diatas 0.5 sebagai High, dibawah 0.5 sebagai Low
        if ratio >= 0.5:
            print(f'{row['Project_ID']}: {ratio} (High)')
        else:
            print(f'{row['Project_ID']}: {ratio} (Low)')
        #nanti ratio sama kategori nya di masukin ke df lagi
    # buat hasil nya sesuai apa yg dikasih kondisi nya aja, nanti tinggal jelasin dan kasih bukti perhitungan manual nya

PLTS-JABW-001: 0.0004318181818181818 (Low)
PLTS-JATIM-001: 0.0004494830944413924 (Low)
PLTS-NTB-001: 0.00044444444444444447 (Low)
PLTS-NTT-001: 0.0005 (Low)
PLTS-SULS-001: 0.00047808764940239046 (Low)

<strong>ðŸ”¹Example Output :</strong>  
PLTS-NTT-001: 0.50 (High)  
PLTS-JATIM-001: 0.45 (Low)